# action.yaml
name: 'Trigger Deployment in Planerios AWS ECS'
description: 'use multiple bash scripts to trigger a deployment and run updates'
inputs:
  PLANERIO_SERVICE_NAME:
    description: 'name of the Planerio service you want to deploy'
    required: true
  PLANERIO_STATIC_ENVIRONMENT_NAME:
    description: 'planerio environmnt you want to deploy to e.g.: dev, stage'
    required: true
  BUILDNUMBER:
    description: 'number of build'
    required: true
  BRANCHNAME:
    description: 'name of branch'
    required: true
  COMMITHASH:
    description: 'commithash'
    required: false
  S3OBJECTVERSION:
    description: 's3 object version'
    required: false
  KAFKA_TOPICS_JSON:
    description: 'kafkaTopics to update'
    required: false
runs:
  using: 'composite'
  steps:
    - run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
      env:
        PLANERIO_SERVICE_NAME: ${{ inputs.PLANERIO_SERVICE_NAME }}
        PLANERIO_STATIC_ENVIRONMENT_NAME: ${{ inputs.PLANERIO_STATIC_ENVIRONMENT_NAME}}
        BUILDNUMBER: ${{ inputs.BUILDNUMBER }}
        BRANCHNAME: ${{ inputs.BRANCHNAME }}
        COMMITHASH: ${{ inputs.COMMITHASH }}
        S3OBJECTVERSION: ${{ inputs.S3OBJECTVERSION }}
        KAFKA_TOPICS_JSON: ${{ inputs.KAFKA_TOPICS_JSON }}

