name: Test Coverage Validator
description: Validates test coverage against a target threshold

on:
    workflow_call:
        inputs:
            fail-under:
                description: "Target coverage percentage (0-100)"
                type: number
                default: 80
            coverage-path:
                description: "Path to coverage reports (uses common defaults if not specified)"
                type: string
                default: "coverage/clover.xml"
            compare-branch:
                description: "Branch to compare coverage against"
                type: string
                default: ${{ github.event.pull_request.base.ref }}
            artifact-name:
                description: "Name of the artifact containing coverage reports"
                type: string
                default: "coverage-xml"
jobs:
    check-coverage:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0 # Fetch all history so that diff-cover can compare branches

            - name: Fetch comparison branch
              run: git fetch origin ${{ inputs.compare-branch }}:refs/remotes/origin/${{ inputs.compare-branch }}
              continue-on-error: true

            - name: Download coverage artifact
              uses: actions/download-artifact@v4
              with:
                  name: ${{ inputs.artifact-name }}
                  path: ./coverage-download

            - name: Extract coverage artifact
              run: |
                  mkdir -p $(dirname ${{ inputs.coverage-path }})
                  cp -r ./coverage-download/* $(dirname ${{ inputs.coverage-path }})/

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"

            - name: Install diff-cover
              run: pip install diff-cover

            - name: Fetch base branch for comparison
              run: |
                  git fetch origin ${{ github.event.pull_request.base.ref }}
                  git checkout ${{ github.event.pull_request.head.sha }}

            - name: Replace path in the xml
              run: |
                  # replace #CURRENT_DIR# in path in the xml file with CURRENT_DIR
                  CURRENT_DIR=$(pwd)
                  sed -i "s|#CURRENT_DIR#|$CURRENT_DIR|g" ${{ inputs.coverage-path }}

            - name: Check coverage
              run: |
                  diff-cover ${{ inputs.coverage-path }} --compare-branch=origin/${{ inputs.compare-branch }} --fail-under=${{ inputs.fail-under }}
